### ISSUE TITLE
Maybe integrate somehow with the Owl?

### ISSUE THREAD

**Issue by XVilka** [Chris00/ocaml-curve-sampling#2]
As you might already known, there is an [Owl](https://ocaml.xyz/) project for developing scientific computing infrastructure for OCaml. They are actively maintained and even have a [few good ideas of future directions](https://ocaml.xyz/project/proposal.html), see [their GitHub repositories](https://github.com/owlbarn/).
![](https://ocaml.xyz/_static/owl_logo_4.png)

**Comment by Chris00** [comment]
This library is obviously usable as it is from OWL.  May you clarify what kind of integration you have in mind?
